wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1647339516
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      - 8
      - 16
      4: 3.8.12
      5: 0.12.11
      8:
      - 3
      - 5
architecture:
  desc: null
  value: AENN
batch_size:
  desc: null
  value: 32
convert_to_dbz:
  desc: null
  value: true
downscale256:
  desc: null
  value: true
epochs:
  desc: null
  value: 30
filter_no_rain:
  desc: null
  value: avg0.01mm
g_cycles:
  desc: null
  value: 3
l_adv:
  desc: null
  value: 0.003
l_rec:
  desc: null
  value: 1
label_smoothing:
  desc: null
  value: 0.2
load_prep:
  desc: null
  value: true
lr_d:
  desc: null
  value: 0.0001
lr_g:
  desc: null
  value: 0.0001
model:
  desc: null
  value: GAN
norm_method:
  desc: null
  value: minmax
rec_with_mae:
  desc: null
  value: false
rnn_type:
  desc: null
  value: GRU
server:
  desc: null
  value: RU
train_data:
  desc: null
  value: datasets/train_randomsplit.npy
val_data:
  desc: null
  value: datasets/val_randomsplit.npy
x_length:
  desc: null
  value: 6
y_is_rtcor:
  desc: null
  value: true
y_length:
  desc: null
  value: 3
